### ISSUE TITLE
When defualt_plugin should be used?

### ISSUE THREAD

**Issue by lukaszo** [Huawei-PaaS/CNI-Genie#100]
According to this demo https://asciinema.org/a/120340 cAdvisor is used when no plugin was selected:
```
cni: ""
```
but current behavior is different. When there are no annotations then `default_plugin` is used. When there are ANY annotations then OR when there is empty `cni` annotation then cAdvisor is used.

The end result is that `default_plugin` is only used when pod has no annotattions. 

Is this an expected behavior or is it bug?

**Comment by sushanthakumar** [comment]
As per the current implementation we have, If "Annotation" is blank, it will select default_plugin.
Our expectation is like
1) If "Annotation" is blank/not present, it should select default_plugin
2) If "Annotation" is not blank and it is containing some non cni attributes (can be any standard pod things), it should still select default_plugin as no cni info provided
3) If "cni" is not nil, it means plugin(s) provided in cni should be taken
4) If cni ="" or cni annotation itself is not provided, then network annotation should be checked. If network is provided, it should be considered
5) Finally (means cni=""), smart plugin should be selected

Currently Step 2 is not working as per the expectation, we can have an issue for this and fix this

**Comment by sushanthakumar** [comment]
If u guys have any doubts/concerns/suggestions, pls feel free to discuss here

**Comment by lukaszo** [comment]
Txh for clarification. Should I create a new issue for step 2?

**Comment by lukaszo** [comment]
Actually it was easier to fix https://github.com/Huawei-PaaS/CNI-Genie/pull/102
