### ISSUE TITLE
Incorrect value under multi-ip-preferences

### ISSUE THREAD

**Issue by ramukima** [Huawei-PaaS/CNI-Genie#130]
Even though I deploy a Pod with just a single network my pod should connect to, the following incorrect information is filled-in by Genie in my Pod annotation post deployment.

Describe Pod shows -
```
Annotations:    cni=calico
                multi-ip-preferences={"multi_entry":2,"ips":{"":{},"ip1":{"ip":"192.168.243.214","interface":"eth0"}}}
```

Notice the first empty entry in the 'ips' map and the 'multi_entry' value as '2'.

**Comment by sushanthakumar** [comment]
@ramukima , regarding above observation
1) As per latest implementation, multi-ip-preference will be shown only if pod is going to have more than one ip. Incase of single ip, pod ip address field itself can be referred and user dont have to add multi-ip-reference format in pod yaml while creating the pod, update into pod annotation will be automatically taken incase of multiple ips
2) wrong multi_entry value : We could not observe such issue with latest code, in case you still encounter same with latest code, we can still check further 
3) first empty entry in the 'ips' map : yes , this is an issue and we have raised below PR to fix this issue
https://github.com/Huawei-PaaS/CNI-Genie/pull/131

For latest genie installation, you can use
kubectl apply -f https://raw.githubusercontent.com/Huawei-PaaS/CNI-Genie/master/conf/1.8/genie-plugin.yaml

For any clarification, you can get back to us

**Comment by sushanthakumar** [comment]
Closing this issue, if facing such issues again, pls revert back
