### ISSUE TITLE
Deployment script to check available CNI plugins and test them

### ISSUE THREAD

**Issue by kshafiee** [Huawei-PaaS/CNI-Genie#14]

**Comment by karunchennuri** [comment]
@kshafiee Please confirm if the below scope works to meet the expectation.

**Scope:**
1. Identify existing CNI plugins running on the node
2. Install missing plugins on the node 
3. Make CNI-Genie as primary plugin on the node
4. Restart the kubelet
5. Integrate script with 'make test' to run e2e tests, which should succeed.

**Comment by kshafiee** [comment]
@karunchennuri let's not do step 2 to ensure this same script can run on any node regardless of whether it runs all or only some of the CNI plugins

**Comment by karunchennuri** [comment]
I think we should make this more comprehensive:

1.  create a daemon set that configures conf file and genie bin into /etc/cni/net.d or /opt/cni/bin
2.  Restart kubelet so that genie takes precedence over existing cni plugin that cluster might have been configured with.

**Comment by karunchennuri** [comment]
Pt. 2 above is not needed. Make sure the genie conf is lexicographical precedes any other conf file in the same folder. Kubelet auto-picks every time first file in the /etc/cni/net.d

**Comment by karunchennuri** [comment]
[PR #21 ](https://github.com/Huawei-PaaS/CNI-Genie/pull/21) addresses this requirement.

We aren't meeting 1 and 2 yet, for now we expect plugins to be at place.

Created docker [image](https://quay.io/repository/cnigenie/v1.5?tab=tags) for CNI-Genie.
Documented steps to install cni-genie [here](https://github.com/Huawei-PaaS/CNI-Genie/blob/master/docs/GettingStarted.md#installing-as-docker-container).
