### ISSUE TITLE
Failed to git clone CNI-Genie project in windows with git shell

### ISSUE THREAD

**Issue by m1093782566** [Huawei-PaaS/CNI-Genie#142]
```
$ git clone https://github.com/Huawei-PaaS/CNI-Genie.git
Cloning into 'CNI-Genie'...
remote: Enumerating objects: 217, done.
remote: Counting objects: 100% (217/217), done.
remote: Compressing objects: 100% (161/161), done.
remote: Total 14963 (delta 62), reused 162 (delta 47), pack-reused 14746
Receiving objects: 100% (14963/14963), 30.72 MiB | 1.35 MiB/s, done.
Resolving deltas: 100% (5858/5858), done.
Checking connectivity... done.
fatal: cannot create directory at 'vendor/github.com/docker/distribution/contrib                                                                                            /docker-integration/generated_certs.d/localregistry:5440': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry the checkout with 'git checkout -f HEAD'
```

The root cause is the file name of `vendor/github.com/docker/distribution/contrib/docker-integration/generated_certs.d/localregistry:5440` is not valid in windows.

BTW, I am wondering we just copied these files instead of using `go get`.

It's a bug and should be fixed for improving the contributing experience.

**Comment by m1093782566** [comment]
cc @sushanthakumar @satyaranjanp 

@Lion-Wei I assume you have the same trouble?

**Comment by Lion-Wei** [comment]
Yes, and I believe https://github.com/Huawei-PaaS/CNI-Genie/pull/137 can fix this probelm. 
If #137 can got merge soon, we can just delete those file in vendor with ":", I don't think they are useful.

**Comment by sushanthakumar** [comment]
Ok then, we will check that PR and merge

**Comment by m1093782566** [comment]
Close this issue as #137 already went in.
