### ISSUE TITLE
When physical net is not provided in logical network, given plugin should work

### ISSUE THREAD

**Issue by kannanvj** [Huawei-PaaS/CNI-Genie#151]
When physical net is not provided and plugin is provided , it should use that plugin.
It should not throw the error. It needs to be fixed

```apiVersion: alpha.network.k8s.io/v1
kind: Logicalnetwork
metadata:
 name: net1
 namespace: default
spec:
 physicalNet: "phynet1"
 sub_subnet: "10.32.0.0/24"
```

**Comment by m1093782566** [comment]
@sushanthakumar @satyaranjanp

**Comment by sushanthakumar** [comment]
@kannanvj , As per interest shown by you to fix this, assigned to u, thanks

**Comment by sushanthakumar** [comment]
This issue is addressed by below PR
https://github.com/Huawei-PaaS/CNI-Genie/pull/156
