### ISSUE TITLE
No Detailed Steps to address how to make it work with K8S

### ISSUE THREAD

**Issue by hanpenghero** [Huawei-PaaS/CNI-Genie#34]
I installed k8s 1.5.7 with Flannel installed ， and then installed weave on this Env as well . I followed the "GettingStarted.md" to install Genie . And then made the following changes on my env 

1. I changed kubelet parameters with the following items added ( --network-plugin-dir=cni --network-plugin-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin)  and then restart kubelet service .
2. I checked the following directory 

[root@mscp3 net.d]# ls
00-genie.conf  10-calico.conf  10-weave.conf  calico-kubeconfig  calico-tls  genie-kubeconfig
[root@mscp3 bin]# ls
bridge  calico  calico-ipam  dhcp  flannel  genie  host-local  ipvlan  loopback  macvlan  portmap  ptp  sample  tuning  vlan  weave-ipam  weave-net  weave-plugin-2.0.1
[root@mscp3 bin]# 

3. I just run the sample yaml file provided by Genie as following 

apiVersion: v1
kind: Pod
metadata:
        name: tomcat-weave1
        labels:
                app: web
        annotations:
                cni: "weave"
spec:
        containers:
                - name: key-value-store
                  image: tomcat:latest
                  imagePullPolicy: IfNotPresent
                  ports:
                        - containerPort: 8080

4. After running kubectl create -f ..yaml  , I got the ip from Flannel assigned . So it looks the Genie is not working well . 

So based on my description , do you have any suggestion how to make it work , and how to debug the issues . thanks .

**Comment by kshafiee** [comment]
@hanpenghero 

1. if you deploy a cluster using 'kubeadm' as per "GettingStarted.md", you don't need to manually change kubelet parameters. In other words, please use: 
$ kubeadm init --use-kubernetes-version=v1.5.8-beta.0 --pod-network-cidr=10.244.0.0/16
This makes sure 'kubelet', 'kubeadm', 'kubectl', 'kubernetes-cni' versions are ALL consistent. You will have:
![image](https://user-images.githubusercontent.com/7294758/27884704-1272a4ca-618a-11e7-8c49-4be49d9147bf.png)

2. this looks fine!

3. I used the yaml you provided to create the pod:
![image](https://user-images.githubusercontent.com/7294758/27885900-8b059470-618e-11e7-9fef-158d4e46f922.png)
Note that when I look at the logs, this is what I see:
![image](https://user-images.githubusercontent.com/7294758/27885961-d52d529a-618e-11e7-86ac-619414a9dce2.png)

Let's chat on CNI-Genie Slack channel, https://cni-genie.slack.com, and I can walk you through the steps if the above instructions does not help. Also, please have a second look at the GettingStarted page. I added more details.

**Comment by hanpenghero** [comment]
@kshafiee 

Thank u so much for your help on this . BTW can u send me an invitation for joining your group on Slack ? thanks again . Also I am rebuilding all the source code downloaded from Genie-CNI and see whether there is anything wrong with my Env .

**Comment by karunchennuri** [comment]
@kshafiee @hanpenghero 
Can we close this thread if addressed?

**Comment by kshafiee** [comment]
@hanpenghero feel free to re-open if you are still having any issues with the set-up.
