### ISSUE TITLE
cni-genie_k8s_test.go can not change APIServer port

### ISSUE THREAD

**Issue by hanpenghero** [Huawei-PaaS/CNI-Genie#35]
After installed the k8s , the apiserver default listening port is on 6443 instead of 8080 , but when I run make test , I can see errors listed below . And I changed the 8080 to 6443 in cni-genie_k8s_test.go  and run it again . But still have the same errors . 

CNIGenie
/usr/lib/golang/src/github.com/Huawei-PaaS/CNI-Genie/cni-genie_k8s_test.go:492
  Add nocni networking for Pod
  /usr/lib/golang/src/github.com/Huawei-PaaS/CNI-Genie/cni-genie_k8s_test.go:472
    using cni-genie for configuring nocni CNI
    /usr/lib/golang/src/github.com/Huawei-PaaS/CNI-Genie/cni-genie_k8s_test.go:470
      should succeed nocni networking for pod [It]
      /usr/lib/golang/src/github.com/Huawei-PaaS/CNI-Genie/cni-genie_k8s_test.go:469

      Expected error:
          <*url.Error | 0xc8202ca420>: {
              Op: "Post",
              URL: "http://localhost:8080/api/v1/namespaces/test/pods",
              Err: {
                  Op: "dial",
                  Net: "tcp",
                  Source: nil,
                  Addr: {
                      IP: "\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01",
                      Port: 8080,
                      Zone: "",
                  },
                  Err: {
                      Syscall: "getsockopt",
                      Err: 0x6f,
                  },
              },
          }
          Post http://localhost:8080/api/v1/namespaces/test/pods: dial tcp [::1]:8080: getsockopt: connection refused
      not to have occurred

      /usr/lib/golang/src/github.com/Huawei-PaaS/CNI-Genie/cni-genie_k8s_test.go:448
------------------------------

**Comment by karunchennuri** [comment]
https://github.com/Huawei-PaaS/CNI-Genie/blob/master/cni-genie_k8s_test.go#L101
may be causing the issue. I'll take a look.

**Comment by karunchennuri** [comment]
@hanpenghero updated test case now is on master branch

**Comment by karunchennuri** [comment]
'am closing this issue for now. Fix is part of master branch now.
