### ISSUE TITLE
End-to-end Multi-network solution using CRD & cni-genie

### ISSUE THREAD

**Issue by kshafiee** [Huawei-PaaS/CNI-Genie#38]
The end-to-end solution should look like this:

![image](https://user-images.githubusercontent.com/7294758/28141560-f7bf5e60-6711-11e7-8904-5387780c3af3.png)

**Comment by sushanthakumar** [comment]
This is getting realised through

**Comment by sushanthakumar** [comment]
This is getting realised through

**Comment by sushanthakumar** [comment]
This is getting realised through 
https://github.com/Huawei-PaaS/CNI-Genie/pull/85
and https://github.com/Huawei-PaaS/CNI-Genie/pull/83
This issue can be closed
