### ISSUE TITLE
network policy for multiple IP scenario

### ISSUE THREAD

**Issue by YYGCui** [Huawei-PaaS/CNI-Genie#40]
For the multiple IP scenario, calico and weave plugin is used in my k8s environment.
And when I set namespace ingress as `defaultDeny`, only the eth0 link can be denied.

So is it the normal action? And is there a way to set network policy to all IP link (eth0, eth1, ...) ?

**Comment by kshafiee** [comment]
@YYGCui 
Can you help me reproduce this please?
2. [Calico Network Policy](https://github.com/projectcalico/k8s-policy#calico-network-policy-for-kubernetes) pod is running on your k8s cluster
2. you create a Pod with 2 IP addresses (eth0 with IP address from calico, eth1 with IP address from weave)
3. Do you create a NetworkPolicy object in k8s? OR do you create a namespace like this?
![image](https://user-images.githubusercontent.com/7294758/28186170-fd3e5342-67ce-11e7-87a9-838a4e12135c.png)

Since "Calico Network Policy" enforces policy on top of networking, could it be possibly hard-coded to 'eth0'?

**Comment by YYGCui** [comment]
I checked the weave-npc log and found the root cause. For kubernetes, it only know the IP reported to him and set it as the `podIP`.

For the network policy controller, it get the `podIP` to set iptables rules.

So here weave-npc got the `podIP` (actually the eth0 ip from calico) to set iptables rule.

So if we want to set network policy to mutiple networks, I think we should custom the `npc` to make it get IP from pod annote `mulitple-ip-reference`.

**Comment by kshafiee** [comment]
Interesting observation! @karunchennuri

**Comment by YYGCui** [comment]
@kshafiee so great! for now, I will custom it for temporary use.

Another issue: I use these CNI plugins in k8s version 1.6, and I think it's better to load CNI conf(such as 10-calico.conf) than hard code

**Comment by kshafiee** [comment]
@YYGCui that issue is to be addressed by PR #30 
It yet to be tested more thoroughly, i.e., with different plugins, to be ready to merge to master

**Comment by YYGCui** [comment]
@kshafiee there is a problem when use CNI plugin `canal`
canal conf 10-canal.conf is like:
```
{
    "name": "canal",
    "type": "flannel",
    "delegate": {
      "type": "calico",
      "etcd_endpoints": "***",
      "log_level": "info",
      "policy": {
          "type": "k8s",
          "k8s_api_root": "***",
          "k8s_auth_token": "***"
      },
      "kubernetes": {
          "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    }
}
```
it is use CNI plugin `flannel` and `calico`, so there is no `type` named `canal`.
maybe it's better to match the conf filename with cniName

**Comment by kshafiee** [comment]
@YYGCui I did make [changes ](https://github.com/Huawei-PaaS/CNI-Genie/pull/30/commits/e6dd87a209d000eef00e72f7f16fbbf56b8edda2#diff-13f598c0288e7d988d204653ccc9ae2aR401)to match cniName with filename. Additionally, thsi PR #30 enables cni-genie to pickup any new plugin as long as both the conf file & the binary exist under /etc/cni/net.d & /opt/cni/bin

@karunchennuri will do a review and merge shortly if there's no issues with the PR

**Comment by m1093782566** [comment]
@kshafiee @sushanthakumar I think we can close this issue now since #30 already got merged.

**Comment by sushanthakumar** [comment]
This can be closed as all the cases for conf and conflist are already handled
