### ISSUE TITLE
Meet an error when I use CNI-Genie

### ISSUE THREAD

**Issue by TrevorTaoARM** [Huawei-PaaS/CNI-Genie#47]
Hi all:
I am using CNI-Genie on arm64 server now(k8s 1.5.4), But there is an error occurs for which I can not resolve now. Could you provide some help for me?

the configuration is as follows:
1. /etc/cni/net.d/00-genie.conf
{
    "name": "k8s-pod-network",
    "type": "genie",
    "etcd_endpoints": "http://192.168.100.177:2379",
    "log_level": "debug",
    "policy": {
      "type": "k8s",
       "k8s_api_root": "http://192.168.100.177:8080"
      },
    "kubernetes": {
      "kubeconfig": "/etc/cni/net.d/genie-kubeconfig"
    }
}
2. /etc/cni/net.d/10-flannel.conf:

{
  "name": "flannel",
  "type": "flannel",
  "subnetFile": "/run/flannel/subnet.env",
  "dataDir": "/var/lib/cni/flannel",
  "delegate": {
    "bridge": "kbr0",
    "isDefaultGateway": true
  }
}
and the flannel network is ok by previous work;
3.  the Pod to be deployed:
apiVersion: v1
kind: Pod
metadata:
  name: genie-test-pod3
  labels:
    apps: busybox-genie-test
  annotations:
    cni: flannel
spec:  # specification of the pod's contents
  restartPolicy: Never
  containers:
  - name: genie-test-pod
    image: "arm64v8/busybox"
    stdin: true
    terminationMessagePath: /dev/termination-log
    tty: true

But the following error/events occured when create the pod:
#kubectl describe pod genie-test-pod

......................

Events:
  FirstSeen     LastSeen        Count   From                            SubObjectPath   Type            Reason          M
  ---------     --------        -----   ----                            -------------   --------        ------          -
  24m           24m             1       {default-scheduler }                            Normal          Scheduled       So fed25-k8sminion2
  23m           7m              81      {kubelet fed25-k8sminion2}                      Warning         FailedSync      E "SetupNetwork" for "genie-test-pod_default" with SetupNetworkError: "Failed to setup network for pod \"genie-test-pod_de4068b)\" using network plugins \"cni\": CNI Genie Add IP internal error: CNI Genie error at addNetwork: no plugin name pr

  24m   7m      82      {kubelet fed25-k8sminion2}              Warning MissingClusterDNS       kubelet does not have Clute Pod using "ClusterFirst" policy. Falling back to DNSDefault policy.
  4m    4m      1       {kubelet fed25-k8sminion2}              Warning FailedSync              Error syncing pod, skippinie-test-pod_default" with SetupNetworkError: "Failed to setup network for pod \"genie-test-pod_default(ec26bffc-831e-11eplugins \"cni\": CNI Genie Add IP internal error: CNI Genie error at addNetwork: no plugin name provided; Skipping pod"
, failed to "KillContainer" for "POD" with KillContainerError: "operation timeout: context deadline exceeded"

**Comment by karunchennuri** [comment]
@TrevorTaoARM @kshafiee 
as per the error log shaed 'am seeing error message that "CNI Genie error at addNetwork: no plugin name provided" 

Can you please put a log in the below snipped of the code and see what's going on?
https://github.com/Huawei-PaaS/CNI-Genie/blob/master/genie/genie-controller.go#L117 


Also please make sure your yaml definition for pod follows this syntax https://github.com/Huawei-PaaS/CNI-Genie/blob/master/sampleyamls/pod-flannel.yaml

Having said that in your pod definition can you try changing

annotations:
   cni: "flannel"

Try adding double quotes and see what happens.

**Comment by kshafiee** [comment]
@TrevorTaoARM please update /etc/cni/net.d/10-flannel.conf as follows:

![image](https://user-images.githubusercontent.com/7294758/29541074-ade60994-8686-11e7-8fec-aa66796abdcc.png)

**Comment by TrevorTaoARM** [comment]
@karunchennuri @kshafiee 
I have tried with cni: "flannel" first, and it does not work; then I tried cni: flannel, it does not work either;
I checked /opt/cni/bin:
![image](https://user-images.githubusercontent.com/29970645/29596067-dc582d4e-87ed-11e7-8856-bbc6d6f829ec.png)
Actually I have used the flannel cni plugin solely and Multus cni plugin with 2 flannel plugins in this environment, they are all ok.

**Comment by kshafiee** [comment]
@TrevorTaoARM let's have a chat on https://kubernetes.slack.com or https://cni-genie.slack.com to fix your problem. i already invited you on https://cni-genie.slack.com

**Comment by satyaranjanp** [comment]
@TrevorTaoARM , looked into this issue, current delegate info of genie is not taking parameters provided in your conf, working on this to make it work with above conf

**Comment by sushanthakumar** [comment]
Below PR has been raised to solve this issue and under review
https://github.com/Huawei-PaaS/CNI-Genie/pull/53

**Comment by sushanthakumar** [comment]
Below PR resolves this issue
https://github.com/Huawei-PaaS/CNI-Genie/pull/53
If any more support needed, happy to help
