### ISSUE TITLE
install k8s with CNI-Genie and encountered the following issue

### ISSUE THREAD

**Issue by hanpenghero** [Huawei-PaaS/CNI-Genie#48]
I installed k8s with flannel , and then installed weave , but when I used weave as the annotation , encountered the following issue . 

8月 23 15:11:47 hp-k8s-4 kubelet[17877]: CNI Genie cniName=weave
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: CNI Genie files =[/etc/cni/net.d/00-genie.conf /etc/cni/net.d/10-flannel.conf /etc/cni/net.d/10-weave.conf]
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: CNI Genie confFromFile ={ k8s-pod-network genie {   <nil> <nil> [] []} 0 hp-k8s-4 kubernetes   info {k8s  eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJrdWJlLXN5c3RlbSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJkZWZhdWx0LXRva2VuLTg0enRmIiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImRlZmF1bHQiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIxNmVjODAyYS04MjY4LTExZTctODNjOC0wMDUwNTZiY2JmZDkiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6a3ViZS1zeXN0ZW06ZGVmYXVsdCJ9.pBOr1bisfN5nBp9vhMaZVmQfc8G52McK_LKDch64ylhKLJbQ0rVWDxmLUqwvQGKEqJh2ffp3RtpnwFn7to8bjHnsio-5E5L7xOkUDPG5gl6ThUwKXWDM28dCBdmm0Z4L3cNP-f9KYjK-mMT2lo0SIc61UexOiiCMYQc1kPnVGtw8g3iUaMxuVZSX8xzob5PQrIYkKQHlLmECV9bLmCCwbJ8gOi50dNFD3Soy3teWlhs7RI29KQbAEpYMQZfqs-BWe19xL__wytNcStGp7zWSs9ucEzFq9j_6ReIiqo2V9bv84mk39EJrlquuG8qeJGDwD1VwQxIxvyDZmkfeD760JA   } {https://10.253.0.1:443 /etc/cni/net.d/genie-kubeconfig } {{{ {[]}}}}     {   {     } {  }}    http://: romanaSegment}
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: CNI Genie confFromFile ={ k8s-pod-network flannel {   <nil> <nil> [] []} 0      {     } {  } {{{ {[]}}}}     {bridge  info {     } {  }}     }
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: CNI Genie confFromFile ={ weave weave-net {   <nil> <nil> [] []} 0      {     } {  } {{{ {[]}}}}     {   {     } {  }}     }
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: CNI Genie cniName file found!!!!!! confFromFile.Type =weave-net
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: E0823 07:11:47.934415   17989 docker_manager.go:372] NetworkPlugin cni failed on the status hook for pod 'centos2' - Unexpected command output Device "eth0" does not exist.
8月 23 15:11:47 hp-k8s-4 kubelet[17877]: with error: exit status 1

Do you have any suggestion ?

**Comment by xiaods** [comment]
"eth0" does not exist.

**Comment by kshafiee** [comment]
@xiaods @hanpenghero  we started working on this Issue, we will update you shortly

**Comment by sushanthakumar** [comment]
@hanpenghero , Can you please share the pod yaml file and conf file of weave (in dir /etc/cni/net.d) so that we can analyse it

**Comment by sushanthakumar** [comment]
@hanpenghero, will contact u through https://cni-genie.slack.com to get above details for analysis

**Comment by sushanthakumar** [comment]
Talked to hanpenghero, it works fine for him now in his env. Confirmed to close it, Thanks

**Comment by xiaods** [comment]
what? any sharing with this? please update doc to sharing it.thanks a lot.

**Comment by sushanthakumar** [comment]
@xiaods , As per chat with hanpenghero, the old environment does not exists and after moving to new, he does not face this issue. Incase u are facing this or similar issue, would like to look into it, U can pass us the details. we can chat through https://cni-genie.slack.com as well.. thanks
