### ISSUE TITLE
no default root on the running pod with Flannel plugin + k8s 

### ISSUE THREAD

**Issue by hanpenghero** [Huawei-PaaS/CNI-Genie#52]
I encountered another issue on flannel by leveraging Genie , after the pod running the default route is not existing in the pod , so as to the communication between pod is working but when I want to ping host's ip it is not working . the workaournd is to set the default route by command route add -net 0.0.0.0 ...... , also I checked the website https://github.com/containernetworking/cni/issues/184 , it seems the default 10-flannel.conf should be changed , but it did not work for me .

from the website we can see , sounds like CNI has already added a new parameter "isDefaultGateway" to address this issue . But I tried it on my env , it is not working .
{
    "name": "myflannel",
    "type": "flannel",
    "delegate": {
        "bridge": "myflannelbr",
        "isDefaultGateway": true
    }
}
So I am not sure if Genie can  support this config file ?

**Comment by kshafiee** [comment]
@sushanthakumar

**Comment by sushanthakumar** [comment]
@hanpenghero/@kshafiee , This issue is similar to https://github.com/Huawei-PaaS/CNI-Genie/issues/47. Current genie code is not supporting isDefaultGateway field in its delegate structure. We are working on to fix this, Update u soon

**Comment by sushanthakumar** [comment]
Below PR has been raised to solve this issue and under review
https://github.com/Huawei-PaaS/CNI-Genie/pull/53

**Comment by hanpenghero** [comment]
@sushanthakumar this issue has been fixed ? I want to have a test on the new code . not sure if it is ready . thx

**Comment by sushanthakumar** [comment]
@hanpenghero , yes it is merged through #53, U can take the latest, do let me know incase u face any issue, thanks

**Comment by hanpenghero** [comment]
@sushanthakumar I did a test on my env , I downloaded the latest code and recompiled on my env , and then replace the old genie file under /opt/bin/genie . but it looks the default root is still not there .

[root@hp-full-1 ~]# kubectl exec -ti cni-flannel-1 sh
sh-4.2# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.254.0.0      10.254.66.1     255.255.0.0     UG    0      0        0 eth0
10.254.66.0     0.0.0.0         255.255.255.0   U     0      0        0 eth0

But I did not update quay.io/cnigenie/v1.5 image , so still using the old genie service running on the container , is that correct ?

**Comment by sushanthakumar** [comment]
@hanpenghero, will contact u through slack tomorrow to check this ,thanks

**Comment by hanpenghero** [comment]
it is fixed . thanks .

**Comment by kshafiee** [comment]
@hanpenghero Thanks for the feedback, will close this!
