### ISSUE TITLE
conf file parsing should be generalized

### ISSUE THREAD

**Issue by kshafiee** [Huawei-PaaS/CNI-Genie#57]
Right now, the new calico conf file is not parsed correctly.

**Comment by sushanthakumar** [comment]
Conf file parsing generilazion is acheived through merge of below PR, this issue can be closed

**Comment by sushanthakumar** [comment]
Conf file parsing generilazion is acheived through merge of below PR, this issue can be closed

**Comment by sushanthakumar** [comment]
Conf file parsing generilazion is acheived through merge of below PR, this issue can be closed
https://github.com/Huawei-PaaS/CNI-Genie/pull/73
