### ISSUE TITLE
what's the  difference between multus-cni and CNI-Genie？

### ISSUE THREAD

**Issue by woshihaoren** [Huawei-PaaS/CNI-Genie#61]
Under what circumstances should CNI-Genie be chosen?

**Comment by woshihaoren** [comment]
Maybe multus-cni support plugins more than

**Comment by kshafiee** [comment]
@woshihaoren 

1. CNI-Genie supports 
- similar to Multus, [reference cni plugins](https://github.com/containernetworking/plugins), 3rd party plugins, e.g., Flannel, Calico, Weave Net, Romana, etc., specialized plugins, e.g., SR-IOV
- unlike Multus, supports any 'generic' CNI plugin installed on the host

2. CNI-Genie supports
- similar to Multus, multi-NICs per container
- unlike Multus, multi-NICs per pod
- unlike Multus, assigning any NIC to any plugin of choice in runtime

3. CNI-Genie supports, unlike Multus, Network isolation, i.e., 
- dedicated physical network for a tenant
- Isolated logical networks for different tenants on a shared physical network

4. CNI-Genie supports, unlike Multus, real-time switching between different networks for a given workload

5. CNI-Genie supports, unlike Multus, network selection based on the user-provided measures (smart selection)

**Comment by kshafiee** [comment]
@satyaranjanp @sushanthakumar 
Please add any other features that I may be missing above!

**Comment by woshihaoren** [comment]
@kshafiee  Do you have a demo of 
assigning any NIC to any plugin of choice in runtime  and
dedicated physical network for a tenant and
Isolated logical networks for different tenants on a shared physical network
