### ISSUE TITLE
when cni is empty,genie has panic

### ISSUE THREAD

**Issue by woshihaoren** [Huawei-PaaS/CNI-Genie#63]
I use https://raw.githubusercontent.com/Huawei-PaaS/CNI-Genie/master/conf/1.8/genie.yaml
on k8s 1.8
```
  annotations:
    cni: ""
``` 
when cni is empty, pod can't run and has below error
if cni isn't empyt,it can work
```
Dec  2 16:51:38 k8s-215 kubelet: E1202 16:51:38.311955    2436 cni.go:301] Error adding network: netplugin failed but error parsing its diagnostic message "": unexpected end of JSON input
Dec  2 16:51:38 k8s-215 kubelet: CNI Genie annot= [map[cni:]]
Dec  2 16:51:38 k8s-215 kubelet: CNI Genie End result= %!s(<nil>)
Dec  2 16:51:38 k8s-215 kubelet: panic: runtime error: invalid memory address or nil pointer dereference
Dec  2 16:51:38 k8s-215 kubelet: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x53bc16]
Dec  2 16:51:38 k8s-215 kubelet: goroutine 1 [running, locked to thread]:
```

**Comment by kshafiee** [comment]
@sushanthakumar @satyaranjanp 
We already cover this in our cni-genie_k8s_test.go, right?

**Comment by sushanthakumar** [comment]
@woshihaoren , We got the issue you are facing, will resolve and update u, thanks

**Comment by sushanthakumar** [comment]
@woshihaoren , below PR will fix this issue
https://github.com/Huawei-PaaS/CNI-Genie/pull/74

When u have several network plugins running, For using smart plugin selection feature(cni: ""),
we need to run cadvisor at port 4194 (reference link: https://github.com/google/cadvisor)
Then genie can help to pick a right network based on network usage. If any queries, happy to help
