### ISSUE TITLE
Slack Link Not Working

### ISSUE THREAD

**Issue by FozAhm** [Huawei-PaaS/CNI-Genie#77]
Hi, there is a Slack Link on the Mead GitHub ReadMe however when I click the link it only allows @huawei email holders to join, how can non huawei email holders join?

**Comment by kshafiee** [comment]
@FozAhm I asked our admin to investigate why you could not join. In the meantime I'll be happy to answer any questions or invite you to our slack. Please email me at kaveh.shafiee@huawei.com

**Comment by FozAhm** [comment]
I have sent you a email, thank you so much 👍
