### ISSUE TITLE
Need to deploy pods without annotation

### ISSUE THREAD

**Issue by gopinatht** [Huawei-PaaS/CNI-Genie#98]
We are trying to connect some Kubernetes pods to multiple networks with CNI Genie with the following yaml as required:

```
annotation:
  cni: "network1, network2"
```
However, many of our pods do not need to connect to multiple networks and therefore do not provide the `cni` annotation. Is there a way to connect these pods to a default network (say `network1`) without having to specify a `cni` annotation?

If not, we request this feature as this is a valid usecase in several scenarios.

**Comment by kshafiee** [comment]
@gopinatht as far as I know we are already addressing this issue. I.e., if there is no annotations, the default plugin is used. If there is annotations, but with cni:"" the plugin is selected smartly by genie. @sushanthakumar please confirm that this is in fact the expected behavior. Thx!

**Comment by gopinatht** [comment]
@kshafiee Many thanks for the quick response. If you do not mind me asking, do you know what version this issue was addressed in? We are using the 1.8 version of genie.

**Comment by sushanthakumar** [comment]
@gopinatht , We should below mechanism about selecting plugin in case not specified by user

**Comment by sushanthakumar** [comment]
@gopinatht , As u mentioned, there are many cases in which user want to select some default plugin and not so specific about which plugin to use.  When user keep annotation as blank (like shown below), it is assumed that user wants to use default plugin
![image](https://user-images.githubusercontent.com/30930862/40227786-15c2d06a-5aad-11e8-818f-80fcb4e641ed.png)


We have below mechanism for this case
1) By default, we select "weave" as the plugin. So if weave is installed, pod will comeup and use weave
2) In case user want to use some other plugin as default plugin, it can be mentioned in genie conf file as below. Once this is mentioned, that plugin will be used as default for subsequent pods, user need not bother. This config can be updated/modified at any point of time and will reflect in future run

![image](https://user-images.githubusercontent.com/30930862/40227968-96bb9422-5aad-11e8-8db1-05a505fce243.png)

Point 1 support is available in genie from the begining
Point 2 support is added as part of below contribution

**Comment by sushanthakumar** [comment]
https://github.com/Huawei-PaaS/CNI-Genie/pull/69

**Comment by sushanthakumar** [comment]
Pls let us know if any queries/support needed. If no issues, I shall close this after your check

**Comment by sushanthakumar** [comment]
One more thing I want to mention is defining "annotations:" is also not needed to indicate deafult plugin, it can simply be like below also without mention of annotation
![image](https://user-images.githubusercontent.com/30930862/40236724-1450de7e-5acc-11e8-8402-5e73dade4eb9.png)

**Comment by gopinatht** [comment]
@sushanthakumar Many thanks for the detailed response. I will test this approach with `default_plugin` and get back to you in a day.

**Comment by gopinatht** [comment]
@sushanthakumar I can confirm that using the `default_plugin` approach solved our problem. I will close this case for now and reopen it if I see more problems.

Thanks again for the help.

**Comment by gopinatht** [comment]
@sushanthakumar I found a bug in the way annotations are handled with CNI genie. If a pod contains `annotations` but no `cni` annotation, the `default_plugin` is not used.

For instance, after installing CNI genie, we tried to install the [etcd operator helm chart](https://github.com/kubernetes/charts/tree/master/stable/etcd-operator) with the following commands:

```
helm install --name voltha-etcd --set etcdCluster.size=1 stable/etcd-operator
helm upgrade --set etcdCluster.size=1 --set customResources.createEtcdClusterCRD=true \
voltha-etcd stable/etcd-operator
```

We get the error:

```
Warning  FailedCreatePodSandBox  2m (x12 over 2m)  kubelet, k8s-01    Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "etcd-cluster-0000_default" network: CNI Genie Add IP internal error: CNI Genie error at ParsePodAnnotations: CNI Genie failed to retrieve CNS list from cAdvisor = unable to get "get all containers info" from "http://127.0.0.1:4194/api/v1.3/containers": Post http://127.0.0.1:4194/api/v1.3/containers: dial tcp 127.0.0.1:4194: connect: connection refused, result: %!!(MISSING)s(<nil>)
```

It looks like CNIGenie is trying to query CAdvisor for a possible network if the `cni` annotation is not given. CNIGenie should really be using the `default_plugin` provided.

**Comment by sushanthakumar** [comment]
@gopinatht , I retested this feature with etcd scenario and below is my observation
1) Installed genie using the link kubectl apply -f https://raw.githubusercontent.com/Huawei-PaaS/CNI-Genie/master/conf/1.8/genie-complete.yaml (Recently we updated the link to support new features but that should not matter for deafult plugin feature)

2) Set default plugin in conf file
![image](https://user-images.githubusercontent.com/30930862/41228056-9f12ce70-6d94-11e8-8d5a-31e8561bdc8d.png)

3) Installed etcd using helm and observed all pods running with Ips acquired from flannel
![image](https://user-images.githubusercontent.com/30930862/41228088-bbc63aca-6d94-11e8-83f6-84086003316a.png)

4) Genie log details  show that default is picked
![image](https://user-images.githubusercontent.com/30930862/41228234-4108207c-6d95-11e8-9194-a34760c79752.png)

5) Finally did helm upgrade and found it running, did not get above error

6) I also checked for normal pods (not the above etcd) which are having annotations but not cni genie annotations and saw them using default plugin. 

Can u pls check once whether my steps are anything different from yours. You can try genie install from above link. 
Anyway, if still this issue is occurring under any usecase/scenarios, we can definitely check further as default plugin is one common usecase scenario
thanks

**Comment by sushanthakumar** [comment]
@gopinatht , I was going through recently handled issues and found that issue u mentioned is referenced in below issue
https://github.com/Huawei-PaaS/CNI-Genie/issues/100
and it is fixed as part of PR https://github.com/Huawei-PaaS/CNI-Genie/pull/102
That is the reason I am not facing that issue in this latest version
So you can install genie using latest link and i guess it should resolve issue
so u can have a check and feedback us
thanks

**Comment by sushanthakumar** [comment]
@gopinatht, Did u get a chance to verify this, hope it works for u

**Comment by gopinatht** [comment]
@sushanthakumar Thanks for the followup. I have not been able to test yet. I plan to test this week. I am creating a helm chart to deploy Genie and a custom network we use. 

I will close this case for now.

I will let you know how the test goes once I have the results. Thanks again for your help.

**Comment by sushanthakumar** [comment]
ok sure, btw genie helm chart in process of merge, below is the reference PR
https://github.com/kubernetes/charts/pull/5968

**Comment by gopinatht** [comment]
@sushanthakumar I see. Do you have an ETA on when the PR could be merged?
