### ISSUE TITLE
Updating documents to cover all of the new features

### ISSUE THREAD

**Issue by kshafiee** [Huawei-PaaS/CNI-Genie#99]
More specifically, we need to re-structure the existing documents so that in addition to multi-plugin & multi-NIC, we also cover multiple logical networks, multiple physical networks, network policy.

The specific tasks would be
- Update first page: what is genie, why we created genie, what are the major value propositions (use-cases), genie doesn't change k8s default behaviour, i.e., pods with no annotations (Issue #98 ) 
- Update getting started: how to add it to any existing cluster, i.e., deployment automation (single-click to download, build, run, helm charts, etc.)
- Include new demo videos

**Comment by sushanthakumar** [comment]
Some PRs in acheiving this
> https://github.com/Huawei-PaaS/CNI-Genie/pull/106/files
> https://github.com/Huawei-PaaS/CNI-Genie/pull/103/files
> https://github.com/Huawei-PaaS/CNI-Genie/pull/112
